# 작성 양식
# ["숫자+보여줄 제목"]  # 숫자는 0부터 이어져야합니다.
# "힌트" = ["힌트 1", "힌트 2"]
# "길이" = 숫자
# "정답" = ["정답1", "정답2", "정답3"]
# "답개수" = 2  # 답개수 안 쓰면 1개 맞추면 넘어감

["0스파이더맨:파프롬홈 OST - Mysterio Theme"]
"힌트" = ["외국영화", "ㅅㅍㅇㄷㅁ"]
"길이" = 40
"정답" = ["스파이더맨", "spiderman"]
"답개수" = 2

["1이누야샤 OST - 달묘전설"]
"힌트" = ["애니OST", "ㅇㄴㅇㅅ"]
"길이" = 50
"정답" = ["이누야샤", "inuyasha"]
"답개수" = 2

["2마비노기 OST - 어릴적 할머니가 들려주신 옛전설"]
"힌트" = ["게임OST", "ㅁㅂㄴㄱ"]
"길이" = 40
"정답" = ["마비노기", "mabinogi"]
"답개수" = 2

["3셜록 OST - Opening Titles"]
"힌트" = ["영국드라마", "ㅅㄹ"]
"길이" = 50
"정답" = ["셜록", "sherlock"]
"답개수" = 2
